### ISSUE TITLE
1 Akun hanya dapat login satu waktu

### ISSUE THREAD

**Issue by ayenz** [ayenz/Sharif-Judge#1]
Jika suatu akun sedang login, tidak ada lagi yang bisa login akun tersebut

**Comment by pascalalfadian** [comment]
Untuk langkah awal:

1. Buat tabel `shj_logins`, isinya `login_id` (int autoincrement), `timestamp`, `username`, `ip_address` varchar, `last_24h_login_id`
2. Untuk setiap login yang sukses:
    * Bersihkan `shj_logins` yang timestamp nya lebih dari 30x24 jam.
    * Cari entri login terakhir untuk username ini yang IP address nya tidak sama.
    * Tambahkan entri baru, dengan `last_24h_login_id` diisi dengan `login_id` jika timestamp pada langkah sebelumnya < 24 jam.
3. Buat halaman baru dan tabel dari login ini.

**Comment by pascalalfadian** [comment]
Based from last commit cd32ffa5509e0359b226f4a9a6270e92528b8ccf:

* [x] Log hanya diambil 24 jam saja, tidak 30 hari.
* [x] Side menu "Logs" direname menjadi "24-hour log"
* [x] Side menu "Logs" dipindah ke paling bawah menu
* [x] Pada tabel "Last Login" diubah menjadi "Login Time"
* [x] Pada tabel "Last 24 Hour Login ID" diubah menjadi "Log from different IP (< 24 hours)"
* [x] Sebelum tabel, diawali dengan teks berikut:

> Use this table to detect account lendings between students in a pre-seated exam environment. In a pre-seated environment, student should have logged in from only one IP address within the exam time period. Whenever a user logs in from different IP address in the past 24 hours, last column of this table will show link to the previous login that happened. In such case, proctor can analyse from those two logins, whether the same login has been used in different devices (meaning the account had been lent).

**Comment by ayenz** [comment]
Commited [cd32ffa ](https://github.com/ayenz/Sharif-Judge/commit/a1fe10503c5fdbeb4478f7dd31c0751cc9a23a23) & Done :thumbsup:
