### ISSUE TITLE
Perbaikan Terakhir, Sekalian Revisi

### ISSUE THREAD

**Issue by pascalalfadian** [ayenz/Sharif-Judge#13]
Mohon lakukan ini:

* [x] Untuk peringkat, jika ada yang seri, misal: `48, 49, 50, 50, ...` maka berikutnya adalah `52` bukan `52`
* [x] Hapus kolom "#", tidak dibutuhkan
* [x] Mohon buat pull request branch `beta_installer_ftis` ke https://github.com/ftisunpar/Sharif-Judge branch `Version-1`

**Comment by ayenz** [comment]
Update rank system

![screenshot_1](https://user-images.githubusercontent.com/13961708/40771362-5bdbeee4-64e7-11e8-8a1c-2f61bd3a3070.png)

**Comment by ayenz** [comment]
Done :pray:
