### ISSUE TITLE
Branding Teknik Informatika

### ISSUE THREAD

**Issue by ayenz** [ayenz/Sharif-Judge#2]
Attach file logo Sharif Judge

**Comment by pascalalfadian** [comment]
Halo @ayenz ini saya butuh kamu untuk attach logo Sharif Judge (PNG / JPEG) nya ya, supaya bisa saya edit menjadi logo Informatika, dengan dimensi yang sama.

**Comment by ayenz** [comment]
Maaf baru balas Pak @pascalalfadian notifnya tidak masuk ke email.
Terkait logo sudah saya kirimkan ke email Bapak, terima kasih.

**Comment by pascalalfadian** [comment]
Ok ini yang sudah saya modifikasi, mohon pakai yang ini ya..

[SharifJudgeLogo.zip](https://github.com/ayenz/Sharif-Judge/files/1445084/SharifJudgeLogo.zip)

**Comment by pascalalfadian** [comment]
implemented

**Comment by pascalalfadian** [comment]
@ayenz logo Sharif Judge nya, bisa tolong diupdate lagi dengan yang ini? Yang dulu saya salah, itu pakai logo UNPAR.

[SharifJudgeLogo.zip](https://github.com/ayenz/Sharif-Judge/files/1693764/SharifJudgeLogo.zip)

**Comment by ayenz** [comment]
[Implemented](https://github.com/ayenz/Sharif-Judge/commit/e81981f2bdef992591de65886e8baedb4743b770)
Thank you 😃
