### ISSUE TITLE
Implement RADIUS login

### ISSUE THREAD

**Issue by pascalalfadian** [ayenz/Sharif-Judge#3]
Using the following as example (from `User_model`):

```php
    /**
     * Validate User
     *
     * Returns TRUE if given username and password is valid for login
     *
     * @param $username
     * @param $password
     * @return bool
     */
    public function validate_user($username, $password) {
        $this->load->library('password_hash', array(8, FALSE));
        $query = $this->db->get_where('users', array('username' => $username));
        if ($query->num_rows() != 1)
            return FALSE;
        if ($query->row()->username !== $username) // needed (because of utf8_general_ci [ci=case insensitive])
            return FALSE;
        // 1. Check in local database
        if ($this->password_hash->CheckPassword($password, $query->row()->password))
            return TRUE;
        // 2. Check in ActiveDirectory
        $this->load->library('radius');
        $radius = new Radius('<masked>', '<masked>');
        if ($radius->AccessRequest($username, $password)) {
            return TRUE;
        }
        return FALSE;
    }
```

Using RADIUS library from (likely) here: https://github.com/dapphp/radius

**Comment by pascalalfadian** [comment]
@ayenz ini sudah diimplement belum ya? Kalau belum, nanti kamu implement ya, koordinasi dengan @chez14 untuk konfigurasi dan testing nya.

**Comment by ayenz** [comment]
Selamat siang Pak. Fitur login RADIUS dalam proses implementasi. Kebetulan kemarin saya juga sudah berkordinasi dengan Gunawan untuk implementasinya. Semoga fiturnya dapat selesai hari ini atau besok.
Terima kasih.

**Comment by chez14** [comment]
Status judge sekarang sudah di*up*kan siang barusan, saat ini repo ini terdeploy ke:
- http://asd.labftis.net/
- http://asd-lat.ftis.unpar/
- http://asd-quiz.ftis.unpar/

Terima kasih.

Btw saat ini kami sedang mengalami masalah dengan radius, jadi untuk sementara login dengan akun labkom tidak dapat dilakukan. Akan saya follow up saat masalah ini selesai.

**Comment by pascalalfadian** [comment]
Trims untuk update nya!

Oh ya, saya baru ingat kalau untuk quiz, itu mahasiswa login nya locked by IP address ya? Kalau di versi Stillmen tidak ada fitur itu 😮 apa langsung di custom di server nya ya, atau buat branch baiknya?

**Comment by ayenz** [comment]
Selamat siang Pak, Sharif Judge untuk quiz akan saya coba untuk buat branchnya.
Terima kasih.

**Comment by chez14** [comment]
Untuk quiz, sbenernya kita nggak lock by IP, quiznya selalu hanay bisa di akses di local, Pa @pascalalfadian.

**Comment by pascalalfadian** [comment]
Trims Chris, kalau gitu untuk sementara berarti ga masalah ya.

**Comment by chez14** [comment]
Betul pa

**Comment by chez14** [comment]
Btw saat ini issue tentang login sudah teresolve, cuma barusan @ferdianexe nggak sengaja nyalain si ceklis emailnya, jadi anak-anak dapet email nyasar xD yang itu mohon diabaikan saja

Oh btw muncul issue baru, kaya email konfirmasi yang dikirim jadi aneh, seperti yang sampai di inbox email bapak (saya sempat cek), lalu folder assignments mungkin sebaiknya di hapus karna tabrakan dengan virtual urlnya judge untuk `/assignments` hehehe

**Comment by pascalalfadian** [comment]
Oke thanks, kalau ada issue yang bisa dilempar ke @ayenz, minta tolong ayenz aja dalam bentuk issue, sebagai bagian dari skripsi nya dia 😉 (nanti dilaporkan aja di dokumen untuk menambah bobot pengerjaan).

**Comment by pascalalfadian** [comment]
Btw ini udah beres kan @ayenz ? kalau memang sudah, di close aja ya. Trims.

**Comment by ayenz** [comment]
Implemented.
