### ISSUE TITLE
Add User Email are not formatted correctly

### ISSUE THREAD

**Issue by chez14** [ayenz/Sharif-Judge#5]
The add user email are sent with the text token like `{ROLE}` are replaced with the password, etc

The screenshot are attached.
![image](https://user-images.githubusercontent.com/5555026/35503034-7f1aab24-0511-11e8-9c01-220012e1abd9.png)

**Comment by ayenz** [comment]
Done, please try again.
Thank you 😃 .

**Comment by chez14** [comment]
Thanks! Problem Solved.
