### ISSUE TITLE
Cannot create Assignments

### ISSUE THREAD

**Issue by chez14** [ayenz/Sharif-Judge#7]
Pa Husnul come to Admin Room this morning that he cannot make an assignment, i've reseted the permission on `restricted` folder, the path that refers into it, but nothing works.

The error log shows nothing. `/var/log/apache2/error.log` says:

```
[Wed Jan 31 06:25:02.516154 2018] [mpm_prefork:notice] [pid 1734] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Jan 31 06:25:02.516182 2018] [core:notice] [pid 1734] AH00094: Command line: '/usr/sbin/apache2
```

Can you help us to find the bug? Thanks!

**Comment by chez14** [comment]
Finished as discussed on Admin Room.

Thank you!

**Comment by ayenz** [comment]
Error occurs because the `archived_assignments` column in the `shj_assignments` table does not exist.
Solution: add column `archived_assignment` in table `shj_assignments`.

Thank you 😃
