### ISSUE TITLE
Link ke new home of Sharif-Judge

### ISSUE THREAD

**Issue by pascalalfadian** [ayenz/Sharif-Judge#8]
Di add/edit assignment, ada link menuju dokumentasi Sharif-Judge milik mjnaderi. Ini diupdate saja jadi ke https://github.com/ftisunpar/Sharif-Judge/...

Di find-and-replace aja all files https://github.com/mjnaderi/Sharif-Judge/ ke https://github.com/ftisunpar/Sharif-Judge/ supaya tidak terlewat.

![screen shot 2018-02-01 at 08 49 26](https://user-images.githubusercontent.com/5976057/35657021-df684a0a-072c-11e8-9e89-6ed71491d18a.png)

Selain itu, mohon juga update deskripsi di sini https://github.com/ayenz/Sharif-Judge/blob/docs/v1.4/add_assignment.md#allowed-languages

Sehingga merefleksikan perubahan yang sudah kamu lakukan (rasanya sekarang ada upload txt & jar? saya lupa persisnya)

**Comment by ayenz** [comment]
[Implemented](https://github.com/ayenz/Sharif-Judge/commit/726ef16514e0f7f7fb7fe4f4fcc839cf6c80300d).
Upload baru ada penambahan file dengan ekstensi txt. Upload jar belum diimplementasi karena masih mencari cara agar file jar dapat langsung _auto-judge_ (dinilai). Namun jika file jar untuk mode _Upload Only_ (sama seperti mode pengumpulan txt, zip, dan pdf) bisa langsung saya implementasikan.

**Comment by pascalalfadian** [comment]
Ini sudah beres ya
