### ISSUE TITLE
Hapus perbedaan antara admin dan student pada PDF download

### ISSUE THREAD

**Issue by pascalalfadian** [ayenz/Sharif-Judge#9]
Di [Assignments.php](https://github.com/ayenz/Sharif-Judge/blob/Version-1/application/controllers/Assignments.php#L114) kamu sudah menambahkan filter untuk download PDF.

Mohon diubah sedikit, bagian-bagian `&& $this->user->level == 0` ini dihapus saja. Alasannya supaya transparan antara dosen dan mahasiswa, sehingga dosen saat membuat assignment lebih yakin bahwa soalnya tidak akan bisa dibuka.

**Comment by ayenz** [comment]
[Implemented](https://github.com/ayenz/Sharif-Judge/commit/40f3c2671aadfd2164fa98ac00ccac9229dbfcce).
Thank you.
